### ISSUE TITLE
Error: package or namespace load failed for ‘mlr3learners.lightgbm’

### ISSUE THREAD

**Issue by kapsner** [mlr3learners/mlr3learners.lightgbm#6]
Hi @pat-s,

when installing and loading the new "development" branch from a kaggle notebook, I get the following error message:

```
Error: package or namespace load failed for ‘mlr3learners.lightgbm’:
.onLoad failed in loadNamespace() for 'checkmate', details:
call: get0(oNam, envir = ns)
error: lazy-load database '/usr/local/lib/R/site-library/backports/R/backports.rdb' is corrupt
```

This error seems most probably to be related to the new `.onLoad` function, since it doesn't occur when installing the "master" branch (with the old zzz.R from the mlr3learners.template).

A minimal example is [here](https://www.kaggle.com/nonserial/error-debugging/log?scriptVersionId=31504325) (you need to scroll all the way down to the final lines of the log).

Any idea, why this error occurs and how it could be fixed?

**Comment by mllg** [comment]
You need to re-install backports. This sometimes happens if an installation is aborted.

**Comment by kapsner** [comment]
Perfect, thanks @mllg. `install.packages("backports")` solved the issue.
