### ISSUE TITLE
Example Code fails with lightgbm 3.0

### ISSUE THREAD

**Issue by ThomasWolf0701** [mlr3learners/mlr3learners.lightgbm#8]
I ran the example code from you GitHub page and after trying to train the classifier:

learner$train(task, row_ids = 1:120)

I got the following error message:

Error in lightgbm::lgb.prepare(data) : 
  lgb.prepare() was removed in LightGBM 3.0.0. Please use lgb.convert_with_rules()

**Comment by ThomasWolf0701** [comment]
This seems to be the problem:  

  # prepare data for lightgbm
      data = lightgbm::lgb.prepare(data)

Replacing with 
   data = lightgbm::lgb.convert_with_rules(data)
should fix this ?

**Comment by statist-bhfz** [comment]
https://github.com/mlr3learners/mlr3learners.lightgbm/pull/9

**Comment by kapsner** [comment]
fixed with https://github.com/mlr3learners/mlr3learners.lightgbm/commit/0d4dc329bffe057debebb8a1e684164ed291aa67
